name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build-libfaust:
    uses: Simon-L/faust/.github/workflows/libfaust.yml@mfx-gh-actions
  build:
    runs-on: macos-13
    needs: build-libfaust
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: 'echo Hello, world!'
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
